version: 2
defaults:
  working_directory: ~/repo
  docker:
    -
      image: 'circleci/node:8.9.1'
jobs:
  publish:
    docker:
    -
      image: 'circleci/node:8.9.1'
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
workflows:
  version: 2
  tagged-build:
    jobs:
      - publish
