version: 2
defaults:
  working_directory: ~/repo
  docker:
    -
      image: 'circleci/node:8.9.1'
jobs:
  build:
    working_directory: ~/repo
    docker:
      -
        image: 'circleci/node:8.9.1'
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      -
        run: 'npm install'
      -
        save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      -
        persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    working_directory: ~/repo
    docker:
      -
        image: 'circleci/node:8.9.1'
    steps:
      -
        attach_workspace:
          at: ~/repo
      -
        run:
          name: 'Authenticate with registry'
          command: 'echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc'
      -
        run:
          name: 'Publish package'
          command: 'npm publish'
